# Getting and Cleaning Data Course Project
# This script fetches and cleans a data set that was generated
# by collecting data from the accelerometers and gyroscopes
# from the Samsung Galaxy S smartphone.
# The original source of this data is the UCI Machine Learning Repository.

# Three data frames are generated by this script,
# 1) mergedSet: training and test data were merged to generate this frame. 
# only those measurements on the mean and standard deviation for each 
# measurement are retained in this frame.
# 2) fullMelt: This is a molten data set and the first of two tidy data sets
# genrated by this script. The data in this set has not been aggreagted by mean.
# 3) TidyData: Data has been aggregated by mean and variable names rendered more 
# descriptive than those attached to the original data. 

# This script writes TidyData to a space delimited file, "TidySamsungGalaxyData.txt"
# using the write.table() function. It can be read into R using the following command
# read.table("TidySamsungGalaxyData.txt", header = TRUE)

# Additional packages required for running of script 
library(reshape2)

# STEP 1: Download and read needed data files into dataframes 
if(!file.exists("UCI_HAR_Data")) {
    dir.create("UCI_HAR_Data")
}

# Download zip file
zipURL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(zipURL,"./UCI_HAR_Data/temp",method = "curl")

# unzip zip file
unzip("./UCI_HAR_Data/temp", exdir = "./UCI_HAR_Data/")
# Delete zip file
unlink("./UCI_HAR_Data/temp")

# Read training set data into data frame
xtrain <- read.table("./UCI_HAR_Data/UCI HAR Dataset/train/X_train.txt", colClasses = "numeric")
# Read numeric training set labels into data frame
ytrain <- read.table("./UCI_HAR_Data/UCI HAR Dataset/train/Y_train.txt", colClasses = "numeric")
# Read training set subject IDs into data frame
subjectTrain <- read.table("./UCI_HAR_Data/UCI HAR Dataset/train/subject_train.txt", colClasses = "numeric")

# Read test set data into data frame
xtest <- read.table("./UCI_HAR_Data/UCI HAR Dataset/test/x_test.txt", colClasses = "numeric")
# Read numeric test set labels into data frame
ytest <- read.table("./UCI_HAR_Data/UCI HAR Dataset/test/y_test.txt", colClasses = "numeric")
# Read test set subject IDs into data frame
subjectTest <- read.table("./UCI_HAR_Data/UCI HAR Dataset/test/subject_test.txt", colClasses = "numeric")

# Read in table that maps numeric activity labels to character labels such as walking 
activityLabelMap <- read.table("./UCI_HAR_Data/UCI HAR Dataset/activity_labels.txt", 
                               colClasses = c("numeric","character"))

# Read features into data frame. These features will be the names of the data columns for fullSet
features <- read.table("./UCI_HAR_Data/UCI HAR Dataset/features.txt", colClasses = "character")

# STEP 2: Merge the training and test data sets
# Merge training and test data using rbind
mergedSet <- rbind(xtrain,xtest)
# Add names to the merged data set 
names(mergedSet) <- features$V2

# STEP 3: Select only the measurements on the mean and standard deviation for each measurement

# Select those variables that contain "-mean()" or "-std()" 
mergedSet <- mergedSet[,grepl("mean\\()|std\\()", names(mergedSet))]

# STEP 4: Order the merged data by subject ID number and activity label 

# Create a vector of subject IDs. IDs range from 1 to 30 
subjectID <- c(subjectTrain$V1,subjectTest$V1)

# Create a vector of numeric activity labels
activityLabel <- c(ytrain$V1, ytest$V1)

# Add subject IDs and activity labels as columns to the merged data set
mergedSet <- cbind(subjectID,activityLabel,mergedSet)
# order full data set, first by subject ID, then by numeric activity label
mergedSet <- mergedSet[order(mergedSet$subjectID, mergedSet$activityLabel),]

# STEP 5: "Melt Data" as described by Hadley Wickham in his paper "Reshaping Data with
# reshape Package", Journal of Statistical Software, Nov. 2007, Volume 21, Issue 12.

# Convert numeric activity labels to factor. Get factor level names from the activityLabelMap
mergedSet$activityLabel <- factor(as.character(mergedSet$activityLabel), 
                                  labels = tolower(activityLabelMap$V2))
# Convert subjectIDs from numeric to factor.
mergedSet$subjectID <- factor(as.character(mergedSet$subjectID), labels = as.character(seq(1,30)))

# Melt the data using subjectID and activityLabel as ID variables.
# According to the Wickham paper referenced in the comment above,in this form, 
# the resulting data set is tidy. There are 3 identifier (ID) variables (subjectID, 
# activityLabel, and variable) and one measured variable. Each row represents 
# one observation of one variable. 
fullMelt <- melt(mergedSet, id = c("subjectID","activityLabel"))

# The head of fullSet looks like this:
# subjectID activityLabel          variable     value
#         1       walking tBodyAcc-mean()-X 0.2820216
#         1       walking tBodyAcc-mean()-X 0.2558408
#         1       walking tBodyAcc-mean()-X 0.2548672
#         1       walking tBodyAcc-mean()-X 0.3433705
#         1       walking tBodyAcc-mean()-X 0.2762397
#         1       walking tBodyAcc-mean()-X 0.2554682

# STEP 6: Reshape and aggregate data using mean() function
TidyData <- dcast(fullMelt, subjectID + activityLabel ~ variable,mean)


# TidyData is 180 observations of 68 variables. The first 12 rows and fives columns 
# are shown here:
# subjectID      activityLabel tBodyAcc-mean()-X tBodyAcc-mean()-Y tBodyAcc-mean()-Z
#         1            walking         0.2773308      -0.017383819        -0.1111481
#         1   walking_upstairs         0.2554617      -0.023953149        -0.0973020
#         1 walking_downstairs         0.2891883      -0.009918505        -0.1075662
#         1            sitting         0.2612376      -0.001308288        -0.1045442
#         1           standing         0.2789176      -0.016137590        -0.1106018
#         1             laying         0.2215982      -0.040513953        -0.1132036
#         2            walking         0.2785741      -0.017022351        -0.1090575
#         2   walking_upstairs         0.2671219      -0.014385492        -0.1181804
#         2 walking_downstairs         0.2904016      -0.020005077        -0.1108486
#         2            sitting         0.2706121      -0.015042682        -0.1042532
#         2           standing         0.2766503      -0.015541860        -0.1079641
#         2             laying         0.2802306      -0.024294484        -0.1171686

# STEP 7: Label the data set with descriptive variable names

# function to remove unwanted characters from TidyData variable names 
# and make TidyData variable names more descriptive
cleanName <- function(x) {
    # replace any charcters that aren't letters, numbers, "." or "_" with "."
    x <- make.names(x)
    # Replace all occurrences of ".mean" with "Mean"
    x <- gsub(".mean","Mean", x,fixed = TRUE)
    # Replace all occurrences of ".std" with "StandardDeviation"
    x <- gsub(".std", "StandardDeviation", x,fixed = TRUE)
    # replace all remaining "." with ""
    x <- gsub(".","", x,fixed = TRUE)
    # Replace all occurrences of "f" at beginning of each variable name with "frequency"
    x <- sub("^f", "Frequency", x)
    # Replace all occurrences of "t" at beginning of each variable name with "time"
    x <- sub("^t", "Time", x)
    # Replace all occurrences of "Acc" with "Accelerometer"
    x <- sub("Acc", "Accelerometer", x, fixed = TRUE)
    # Replace all occurences of "Gyro" with "Gyroscope"
    x <- sub("Gyro", "Gyroscope", x, fixed = TRUE)
    # Replace all occurrences of "Mag" with "Magnitude"
    x <- sub("Mag", "Magnitude", x, fixed = TRUE)
}

# Call cleanName on each variable name of TidyData
names(TidyData) <- sapply(names(TidyData), cleanName)

# Preface each variable name (except subjectID and activityLabel) with "mean_"
names(TidyData)[c(-1,-2)] <- paste("mean",names(TidyData)[c(-1,-2)], sep = "")

# Replace the underscore in the activity labels "walking_upstairs" and 
# "walking_downstairs" with a space
TidyData$activityLabel <- sub("_"," ",TidyData$activityLabel, fixed = TRUE)

# STEP 8: Write tidy data set to .txt file. Space selected as delimiter
write.table(TidyData,"TidySamsungGalaxyData.txt",sep = " ",row.names = FALSE)

# Delete data frames and vectors that are no longer needed to free up memory
rm(xtrain)
rm(xtest)
rm(ytrain)
rm(ytest)
rm(subjectTrain)
rm(subjectTest)
rm(activityLabel)
rm(features)
rm(subjectID)
rm(activityLabelMap)